// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPRapXRHBSHqUQALVrig6GCEQ-WBbljlI',
    appId: '1:200082581950:web:d7eaa213e389f18fe1f1ef',
    messagingSenderId: '200082581950',
    projectId: 'mhtn-d39dc',
    authDomain: 'mhtn-d39dc.firebaseapp.com',
    storageBucket: 'mhtn-d39dc.appspot.com',
    measurementId: 'G-CJ7H4QD207',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpGgcZLq9unPbLiq510OtoBKI3gbgxVAU',
    appId: '1:200082581950:android:86114460276dd27ce1f1ef',
    messagingSenderId: '200082581950',
    projectId: 'mhtn-d39dc',
    storageBucket: 'mhtn-d39dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLHJUGbLyob8m5cjXvw2zgadl3EY4Kxi8',
    appId: '1:200082581950:ios:775ed878d684b27be1f1ef',
    messagingSenderId: '200082581950',
    projectId: 'mhtn-d39dc',
    storageBucket: 'mhtn-d39dc.appspot.com',
    iosBundleId: 'com.main.mhtn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLHJUGbLyob8m5cjXvw2zgadl3EY4Kxi8',
    appId: '1:200082581950:ios:247b55b0d19137e9e1f1ef',
    messagingSenderId: '200082581950',
    projectId: 'mhtn-d39dc',
    storageBucket: 'mhtn-d39dc.appspot.com',
    iosBundleId: 'com.example.fstore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPRapXRHBSHqUQALVrig6GCEQ-WBbljlI',
    appId: '1:200082581950:web:7d806ff2458f2621e1f1ef',
    messagingSenderId: '200082581950',
    projectId: 'mhtn-d39dc',
    authDomain: 'mhtn-d39dc.firebaseapp.com',
    storageBucket: 'mhtn-d39dc.appspot.com',
    measurementId: 'G-8GLJWNYV5K',
  );

}